### ISSUE TITLE
[QUESTION] how to get the swagger page?

### ISSUE THREAD

**Issue by verajosemanuel** [StatsGary/PlumberWithCaretML_API#1]
HI
How is supposed to access to the swagger page? (I develo using VScode, so no rstudio helpers.....)

`http://localhost:8000`  says `404 not found`

using Rstudio the swagger page url is:

`http://127.0.0.1:8000/__docs__`

and shows:

`http://127.0.0.1:8000/openapi.json`

But I assume this is a Rstudio feature.  is there any way opf getting such info page in browser? 
 (http://127.0.0.1:8000/openapi.json  is 404 in chrome if no Rstudio is involved)
The rest of endpoints seems to work ok

Thanks for an excellent intro to plumber

**Comment by StatsGary** [comment]
This will have the answers to your question: https://rviews.rstudio.com/2018/07/23/rest-apis-and-plumber/.
