### ISSUE TITLE
not training on train_data only

### ISSUE THREAD

**Issue by tomazweiss** [StatsGary/PlumberWithCaretML_API#2]
I'm aware that the main topic of your post is plumber, but you are training the model on the whole dataset:
```
tb_model <- caret::train(stranded_class ~ .,
                         data = stranded,
                         method = 'treebag',
                         verbose = TRUE)
```

**Comment by StatsGary** [comment]
Thanks @tomazweiss . I will amend the GitHub code to support this.  Top marks for the spot of the day!
