### ISSUE TITLE
[QUESTION] Type of predictors in new data do not match that of the training data when using qualitative variables

### ISSUE THREAD

**Issue by RNakamura90** [StatsGary/PlumberWithCaretML_API#3]
Hi StatsGary, I'm following your tutorial on Youtube (I followed and liked your video, thanks!) to build an API for my RF model.
My model contains both quantitative and qualitative variables as predictors. I'm using Postman to send the JSON with the variables I would like to test in my model.
```
{
    "revenue": 24983.22,
    "risk": 39844.33,
    "target_amount": 50000.00,
    "company_years": 10,
    "reason": "Capital_giro",
    "serasa": 2.6,
    "pontualidade": 5,
    "qualidade_divida": 1.4,
    "bancabilidade": 2.2,
    "alavancagem": 3,
    "porte": 1.4,
    "receita_recorrencias": 1.4,
    "respaldo_patrimonio": 3.5,
    "reputacional": 2.5,
    "impacto_covid": 3.5,
    "business_sector": "Comercio",
    "state": "SP",
    "decision_motor": "approved",
    "score": 57
}
```
But I find an error: 
`Error in predict.randomForest(model, newdata = as.data.frame(req$body), : Type of predictors in new data do not match that of the training data.\n`

When I used only R to predict with my RF model, I encountered the same problem as the quantitative variables in the test data did not have the same levels as in the training data. I solved this by bind the first row of the training data into the test data then removing it. Thus, my test data were left with the same levels for the qualitative variables.
To solve this, I tried to create a function (testfun) that basically does this, besides fixing some names and transforming the variables I need into a factor. It's in my prediction function, but I've marked it as a comment so that I'll only test my prediction model first.

```
#* Predict
#* @post /predict
function(req, res){
  #testefun(req, train2)
  data.frame(predict(model, newdata = as.data.frame(req$body), type="prob"))
}
```
Could you help me with this problem? Thanks!

**Comment by StatsGary** [comment]
Sure. I would get rid of them as factors, as you will have a similar problem when you try and put into production. I would recommend dummy encoding the categorical variables. There are many packages to do this in R, but the psych package has a good function for this. 

What I would then do is export the names of your training set out, as the encodings may not be present in the testing or production data. Something like write.csv(names(df)). Then when you create your API use a difference function to look at the difference in the encodings / naming of dummy fields. Copy across the new dummy encodings in your production API and make sure the incoming values are mapped in the same order. 

Shela has a good tutorial on this here: https://sharla.party/post/comparing-two-dfs/. 

Essentially, this boils down to whatever you do in the processing steps to train your model, have to be replicated in the production scripts.

**Comment by RNakamura90** [comment]
Thanks for the support!
